blueprint:
  name: "APC UPS Power Sensor (Automatique)"
  description: >-
    Crée un capteur de puissance instantanée pour un UPS APC.
    Utilise automatiquement la puissance nominale exposée par l'UPS.
  domain: template
  input:
    ups_name:
      name: "Nom de l'UPS"
      description: "Le nom de votre UPS (ex: salon, bureau)"
      selector:
        text:
    
    ups_entity_load:
      name: "Entité de charge UPS (%)"
      description: "L'entité qui indique la charge de l'UPS en pourcentage"
      selector:
        entity:
          filter:
            domain: sensor
            device_class: battery
    
    ups_entity_nominal_power:
      name: "Entité Puissance Nominale (W)"
      description: "L'entité qui indique la puissance nominale de l'UPS"
      selector:
        entity:
          filter:
            domain: sensor
            device_class: power

template:
  - sensor:
      - name: "UPS {{ ups_name | title }} - Puissance"
        unique_id: "ups_power_auto_{{ ups_name | lower | replace(' ', '_') }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        icon: mdi:power-plug-outline
        availability: >-
          {{ states(ups_entity_load) not in ['unavailable', 'unknown'] and
             states(ups_entity_nominal_power) not in ['unavailable', 'unknown'] }}
        state: >-
          {% set load = states(ups_entity_load) | float(0) %}
          {% set nominal = states(ups_entity_nominal_power) | float(520) %}
          {{ (load / 100 * nominal) | round(1) }}
        attributes:
          ups_name: "{{ ups_name }}"
          ups_load_percent: "{{ states(ups_entity_load) | float(0) }}"
          ups_nominal_power: "{{ states(ups_entity_nominal_power) | float(0) }}"
          friendly_name: "UPS {{ ups_name | title }} - Puissance Instantanée"
